### ISSUE TITLE
enableVcsColoring style from Material UI theme

### ISSUE THREAD

**Issue by jerone** [ericcornelissen/pinned-tabs-for-atom#13] opened 2016-03-12 13:57 UTC
There's a small issue with the `enableVcsColoring` indicator from the [Material UI](https://github.com/silvestreh/atom-material-ui) theme being removed:

![atom pinned tabs material ui](https://cloud.githubusercontent.com/assets/55841/13723352/272aa7ac-e862-11e5-8c75-8ae5d24fb960.gif)

**Steps to reproduce:**

1. Install [Atom Material UI](https://atom.io/themes/atom-material-ui) theme.
2. Enable the `enableVcsColoring` setting from the tabs package.
3. Alter a git file.

***

_Atom v1.6.0-beta8
Windows 7
atom-material-ui@1.2.6
pinned-tabs@0.1.13_

**Comment by ericcornelissen** [comment] 2016-03-12 22:00
Are you entirely sure it is caused solely by the ```enableVcsColoring``` setting from Atom Material UI ? I am unable to reproduce the issue with this setup (My guess is it has to do with _Atom v1.6.0-beta8_):
_Atom v1.5.4_
_atom-material-ui@1.2.6_ as UI Theme
_Atom Dark_ as Syntax Theme
_pinned-tabs@0.1.13_

**Comment by jerone** [comment] 2016-03-12 23:07
> Are you entirely sure it is caused solely by the enableVcsColoring setting from Atom Material UI ?

Yes, just did a clean profile, installed Pinned Tabs, set Material UI as theme, enabled `enableVcsColoring` on the Tabs package and got exactly the same result.

**Comment by ericcornelissen** [comment] 2016-03-13 11:04
I got it :smile: The problem is that both are using the ```:after``` of the title element... Its kinda hard to fix this, but I've been working on this on a seperate branch (where I use [file-icons](https://atom.io/packages/file-icons) as a dependencies). I'll speed this process up a bit so this bug will be fixed soon :+1:

**Comment by ericcornelissen** [comment] 2016-03-14 15:52
The issue should be fixed in v0.2.0 :tada: Let me know if you still have problems...

**Closed by ericcornelissen** 2016-03-14 15:52 UTC
Labels: bug

**Comment by jerone** [comment] 2016-03-14 16:53
Confirmed and thanks!
