### ISSUE TITLE
Disabling the package is broken

### ISSUE THREAD

**Issue by xixixao** [ericcornelissen/pinned-tabs-for-atom#38] opened 2017-08-21 11:51 UTC
Repro:
1. Pin a tab.
2. Disable `pinned-tabs`
3. Enable `pinned-tabs`
4. Try to pin a tab. It doesn't work. You will have to disable and reenabled once more for it to work again.

**Comment by ericcornelissen** [comment] 2017-08-22 13:00
Thank you for reporting, I can reproduce the issue. I will look into it as soon as possible!

**Comment by ericcornelissen** [comment] 2017-08-23 15:40
The issue should be solved now so I will close the issue. I won't publish a new release directly though, since this is a very minor issue 👍

**Closed by ericcornelissen** 2017-08-23 15:40 UTC
Labels: bug
